name: magic_receipts
description: Magic Receipts Flutter plugin, allows integration of Magic Receipts into Flutter Android and iOS apps
version: 1.0.1
homepage: https://www.pollfish.com/magic-receipts/
repository: https://github.com/pollfish/flutter-plugin-magic-receipts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pollfish.magicreceipts.flutter
        pluginClass: MagicReceiptsPlugin
      ios:
        pluginClass: MagicReceiptsPlugin
